Add ingress node firewall.
eBPFDevSecTools/ebpf-projects-annotations pull request #63
Opened 2023-04-04 10:32 UTC by dushyantbehl

Opening a PR for https://github.com/eBPFDevSecTools/ebpf-projects-annotations/issues/30

Will ask for merge when all comments have been added.

2023-04-04 10:32 UTC, dushyantbehl commented
Not to be merged yet.

2023-04-04 13:16 UTC, palanik1 requested changes
@dushyantbehl can you add a readme with copyright info as well

2023-04-04 13:20 UTC, palanik1 commented
@dushyantbehl you can change your PR to draft status by clicking on the button under reviewers

2023-04-04 14:43 UTC, palanik1 commented
I probably added it when I was fixing Readme s in the projects..

2023-04-05 05:38 UTC, dushyantbehl commented
@palanik1 its ready for review as the commit https://github.com/eBPFDevSecTools/ebpf-projects-annotations/pull/63/commits/397272eb4fc93fa5b7e3e2813cc532ae89d48de8 adds human comments

2023-04-06 11:49 UTC, palanik1 requested changes
typo -> change to interface

2023-04-06 11:53 UTC, palanik1 requested changes
typo -> change to interface

2023-04-06 11:53 UTC, palanik1 commented on projects/ingress-node-firewall-master/human_annotated/ingress_node_firewall_kernel.c
> +      "description": "This function takes in an xdp_md *ctx and a u32 as ifID. It first calls ip_extract_l4info to extract protocol type, dst port, icmp type and icmp code from the packet. The functi
ingress_inteface -> ingress_interface

2023-04-07 04:32 UTC, palanik1 submitted a review, later dismissed
lgtm.

2023-04-07 05:12 UTC, palanik1 approved these changes
lgtm

2023-04-07 05:12 UTC, merged