Annotated vlan_filter.c, xdp_filter.c, hash_func01.h
eBPFDevSecTools/ebpf-projects-annotations pull request #65
Opened 2023-04-05 09:55 UTC by aashu2303

2023-04-08 14:09 UTC, sdsen requested changes

2023-04-08 14:09 UTC, sdsen commented on projects/suricata-master/human_annotated/bypass_filter.c
> +      "text": "/* Copyright (C) 2018 Open Information Security Foundation\n *\n * You can copy, redistribute or modify this Program under the terms of\n * the GNU General Public License version 2 as
fix the typo by closing the comment.

2023-04-08 14:09 UTC, sdsen commented on projects/suricata-master/human_annotated/xdp_filter.c
>        "author": "",
add author details. Also, please add personal email which you plan to keep using long term.

2023-04-09 04:45 UTC, aashu2303 commented on projects/suricata-master/human_annotated/xdp_filter.c
>        "author": "",
Updated the email address and author details

2023-04-09 04:45 UTC, aashu2303 commented on projects/suricata-master/human_annotated/bypass_filter.c
> +      "text": "/* Copyright (C) 2018 Open Information Security Foundation\n *\n * You can copy, redistribute or modify this Program under the terms of\n * the GNU General Public License version 2 as
Fixed it

2023-04-09 08:08 UTC, sdsen approved these changes
lgtm

2023-04-09 08:09 UTC, merged