Annotated filter.c and lb.c
eBPFDevSecTools/ebpf-projects-annotations pull request #66
Opened 2023-04-05 09:55 UTC by Pymamid

2023-04-08 17:55 UTC, palanik1 requested changes

2023-04-08 17:55 UTC, palanik1 commented on projects/suricata-master/human_annotated/filter.c
> +      "description": "The function extracts the src and dest IP addresses of the IPv4 packet, and checks whether they are in the list of IPs to be dropped. If yes, count of packet drops is incremente
The function extracts the src and dest IP addresses of the IPv4 packet, and checks whether the dst address is  in the list of IPs to be dropped. If yes, count of packet drops is incremented by 1, and function returns 0. If not, function returns -1."

2023-04-08 17:55 UTC, palanik1 commented on projects/suricata-master/human_annotated/lb.c
> +      "description": "The function takes an IPv6 address and computes a hash by bitwise OR of its four octets.",
OR or XOR?

2023-04-09 04:40 UTC, Pymamid commented on projects/suricata-master/human_annotated/lb.c
> +      "description": "The function takes an IPv6 address and computes a hash by bitwise OR of its four octets.",
It should have been XOR. Modified the same.

2023-04-09 07:28 UTC, palanik1 approved these changes

2023-04-09 07:28 UTC, merged

2023-04-09 07:28 UTC, palanik1 commented
lgtm