Add url to stub
eBPFDevSecTools/ebpf-projects-annotations pull request #90
Opened 2023-04-17 07:40 UTC by sdsen

fixes a bug in generating the call depth for loxlb repository

2023-04-18 14:32 UTC, palanik1 requested changes

2023-04-18 14:32 UTC, palanik1 commented on src/annotator.py
> +def path_leaf(path):
Is this function being used anywhere?

2023-04-18 15:16 UTC, palanik1 commented on src/annotator.py
> +def path_leaf(path):
yes please..

2023-04-20 08:52 UTC, sdsen commented on src/annotator.py
> +def path_leaf(path):
done

2023-04-21 12:59 UTC, palanik1 approved these changes

2023-04-21 12:59 UTC, merged